version: '3'



services:

  sleek-airflow:

    image: data-pipeline-airflow:latest

    # build:
    #   context: .
    #   dockerfile: dockerfile

    volumes:

      - ./airflow:/opt/airflow
      - ./scripts:/opt/airflow/scripts  
      - ./data/raw:/opt/airflow/data
      - ./models:/opt/airflow/models



    ports:

      - "8080:8080"



    command: airflow standalone